<?php

declare(strict_types=1);

namespace App\Enums;

enum ErrorCode: string
{
    case SITE_SETTING_NOT_FOUND = 'SITE_SETTING_NOT_FOUND';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    case PHOTO_GALLERY_NOT_FOUND = 'PHOTO_GALLERY_NOT_FOUND';
    case UNLOCKING_NOT_FOUND = 'UNLOCKING_NOT_FOUND';
    case TESTIMONIAL_NOT_FOUND = 'TESTIMONIAL_NOT_FOUND';
    case HOME_PAGE_NOT_FOUND = 'HOME_PAGE_NOT_FOUND';
    case FAQ_NOT_FOUND = 'FAQ_NOT_FOUND';
    case DRAIN_CLEANING_NOT_FOUND = 'DRAIN_CLEANING_NOT_FOUND';
    case CONTACT_US_NOT_FOUND = 'CONTACT_US_NOT_FOUND';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT_FAILED = 'LOGOUT_FAILED';
    case REGISTER_FAILED = 'REGISTER_FAILED';
}
