<?php

declare(strict_types=1);

namespace App\Enums;

enum ErrorCode: string
{
        // Not Found Errors
    case SITE_SETTING_NOT_FOUND = 'SITE_SETTING_NOT_FOUND';
    case PHOTO_GALLERY_NOT_FOUND = 'PHOTO_GALLERY_NOT_FOUND';
    case UNLOCKING_NOT_FOUND = 'UNLOCKING_NOT_FOUND';
    case TESTIMONIAL_NOT_FOUND = 'TESTIMONIAL_NOT_FOUND';
    case HOME_PAGE_NOT_FOUND = 'HOME_PAGE_NOT_FOUND';
    case FAQ_NOT_FOUND = 'FAQ_NOT_FOUND';
    case DRAIN_CLEANING_NOT_FOUND = 'DRAIN_CLEANING_NOT_FOUND';
    case CONTACT_US_NOT_FOUND = 'CONTACT_US_NOT_FOUND';

        // Authentication Errors
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGOUT_FAILED = 'LOGOUT_FAILED';
    case REGISTER_FAILED = 'REGISTER_FAILED';

        // Health Check Errors
    case HEALTH_CHECK_FAILED = 'HEALTH_CHECK_FAILED';

        // Contact Us Errors
    case CONTACT_US_FAILED = 'CONTACT_US_FAILED';
    case CREATE_CONTACT_US_FAILED = 'CREATE_CONTACT_US_FAILED';
    case CREATE_FAQS_FAILED = 'CREATE_FAQS_FAILED';

        // Creation Errors
    case CREATE_TESTIMONIAL_FAILED = 'CREATE_TESTIMONIAL_FAILED';
    case CREATE_SITE_SETTING_FAILED = 'CREATE_SITE_SETTING_FAILED';
    case CREATE_PHOTO_GALLERY_FAILED = 'CREATE_PHOTO_GALLERY_FAILED';
    case CREATE_HOME_PAGE_FAILED = 'CREATE_HOME_PAGE_FAILED';
    case CREATE_FAQ_FAILED = 'CREATE_FAQ_FAILED';
    case CREATE_UNLOCKING_FAILED = 'CREATE_UNLOCKING_FAILED';
    case CREATE_DRAIN_CLEANING_FAILED = 'CREATE_DRAIN_CLEANING_FAILED';

        // General Errors
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

    case UPDATE_CONTACT_US_FAILED = 'UPDATE_CONTACT_US_FAILED';
}
